language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t soya196/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true soya196/docker-react npm run test